/**
 * Hızlı plan arama şeridi — Turlar / Aktiviteler ile aynı kutu tasarımı (#dfe4ec, gölge, ikon+etiket+değer).
 * Büyük gri “mega pill” kapsayıcı yok; alan doğrudan `barCluster` + `fieldCard` / `routeShell` blokları.
 */

export const qp = {
  shell: { width: '100%', minWidth: 0 },

  stickyTop: {
    flexShrink: 0,
    zIndex: 25,
    background: '#fff',
    boxShadow: '0 1px 10px rgba(0,0,0,.05)',
    borderBottom: '1px solid rgba(0,0,0,.06)',
    overflow: 'visible',
  },
  stickyInner: { maxWidth: 1320, margin: '0 auto', padding: '10px 16px 12px', boxSizing: 'border-box' },

  topBarRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    width: '100%',
    boxSizing: 'border-box',
  },
  topBarRowMobile: {
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },

  pillScrollOuter: {
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'hidden',
    WebkitOverflowScrolling: 'touch',
    boxSizing: 'border-box',
    paddingBottom: 4,
    scrollbarGutter: 'stable',
  },

  barCluster: {
    display: 'flex',
    alignItems: 'stretch',
    flexWrap: 'wrap',
    gap: '8px 10px',
    width: '100%',
    minWidth: 0,
    justifyContent: 'center',
  },

  titlePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 8px',
    borderRadius: 999,
    flexShrink: 0,
    alignSelf: 'center',
  },
  spark: { display: 'inline-flex', alignItems: 'center' },
  titleTxt: { fontSize: 12, fontWeight: 700, color: 'var(--text1)', whiteSpace: 'nowrap' },

  barSep: {
    width: 1,
    height: 36,
    background: 'rgba(0,0,0,.10)',
    margin: '0 4px',
    alignSelf: 'center',
    flexShrink: 0,
  },
  barDot: {
    color: 'rgba(0,0,0,.25)',
    fontSize: 14,
    padding: '0 2px',
    alignSelf: 'center',
    userSelect: 'none',
    flexShrink: 0,
  },

  linkedRoute: {
    flex: '1 1 280px',
    minWidth: 0,
    maxWidth: '100%',
  },
  routeShell: {
    display: 'flex',
    alignItems: 'stretch',
    position: 'relative',
    minHeight: 50,
    borderRadius: 10,
    border: '1px solid #dfe4ec',
    background: '#fff',
    boxSizing: 'border-box',
    boxShadow: '0 1px 2px rgba(15,41,74,.05)',
    overflow: 'hidden',
    flex: 1,
  },
  routeSegBtn: {
    flex: '1 1 0',
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 10px',
    border: 'none',
    borderRadius: 0,
    background: 'transparent',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    boxSizing: 'border-box',
  },
  routeSegStatic: {
    flex: '1 1 0',
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 10px',
    boxSizing: 'border-box',
  },
  swapFab: {
    alignSelf: 'center',
    flexShrink: 0,
    margin: '0 -4px',
    zIndex: 2,
    width: 34,
    height: 34,
    borderRadius: 999,
    border: '1px solid #dfe4ec',
    background: '#fff',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(15,41,74,.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },

  fieldCard: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 12px',
    borderRadius: 10,
    border: '1px solid #dfe4ec',
    background: '#fff',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    boxSizing: 'border-box',
    boxShadow: '0 1px 2px rgba(15,41,74,.05)',
    flexShrink: 0,
    flex: '0 1 156px',
    minWidth: 0,
  },
  /** Konum / tarih gibi daha geniş kutular */
  fieldCardGrow: {
    flex: '1 1 200px',
    maxWidth: '100%',
  },
  /** Sadece yerleşim (tıklanabilir kart içi alanlar) */
  fieldCardStatic: {
    cursor: 'default',
  },

  fieldLbl: {
    display: 'block',
    fontSize: 10,
    fontWeight: 650,
    color: '#65758c',
    lineHeight: 1.2,
    marginBottom: 2,
    letterSpacing: '0.01em',
  },
  fieldVal: {
    display: 'block',
    fontSize: 13,
    fontWeight: 800,
    color: '#132d4f',
    lineHeight: 1.28,
    wordBreak: 'break-word',
  },
  fieldPlaceholder: { fontWeight: 600, color: '#9aa9bc' },

  inpInCard: {
    border: 'none',
    background: 'transparent',
    fontSize: 13,
    fontWeight: 800,
    fontFamily: 'inherit',
    color: '#132d4f',
    width: '100%',
    minWidth: 0,
    outline: 'none',
    padding: 0,
    lineHeight: 1.28,
  },
  inpInRoute: {
    border: 'none',
    background: 'transparent',
    fontSize: 14,
    fontWeight: 800,
    fontFamily: 'inherit',
    color: '#132d4f',
    letterSpacing: '0.04em',
    width: '100%',
    minWidth: 48,
    maxWidth: 72,
    outline: 'none',
    padding: 0,
  },
  chipDateInCard: {
    border: 'none',
    background: 'transparent',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'inherit',
    color: '#132d4f',
    padding: 0,
    outline: 'none',
    minWidth: 0,
  },
  chipDateTimeInCard: {
    border: 'none',
    background: 'transparent',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'inherit',
    color: '#132d4f',
    padding: 0,
    outline: 'none',
    width: '100%',
    minWidth: 0,
  },
  selectInCard: {
    border: 'none',
    background: 'transparent',
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'inherit',
    color: '#132d4f',
    padding: 0,
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    minWidth: 0,
  },

  miniPillRow: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    marginTop: 6,
    justifyContent: 'flex-start',
  },
  miniPill: {
    borderRadius: 999,
    border: '1px solid rgba(0,0,0,.14)',
    background: '#fff',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '4px 10px',
    fontFamily: 'inherit',
    color: 'var(--ta-ink)',
  },
  miniPillOn: {
    borderColor: 'var(--ta-accent)',
    background: 'var(--ta-accent-soft)',
    color: 'var(--ta-ink)',
  },

  paxInlineRow: {
    display: 'inline-flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },

  toggleRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  tripMiniPill: {
    borderRadius: 999,
    border: '1px solid rgba(0,0,0,.14)',
    background: '#fff',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '5px 10px',
    fontFamily: 'inherit',
    color: 'var(--ta-ink)',
  },
  tripMiniPillOn: {
    borderColor: 'var(--ta-accent)',
    background: 'var(--ta-accent-soft)',
  },

  searchBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 14px',
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
    border: '1px solid rgba(0,0,0,.15)',
    background: 'var(--ta-ink)',
    color: '#FFFFFF',
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
    alignSelf: 'center',
  },

  clusterFieldsRow: {
    flex: '1 1 auto',
    display: 'flex',
    gap: 10,
    alignItems: 'stretch',
    flexWrap: 'wrap',
    minWidth: 0,
    justifyContent: 'center',
  },
  clusterFieldWrap: {
    flex: '1 1 156px',
    minWidth: 0,
    maxWidth: '100%',
    position: 'relative',
  },
};
